### ISSUE TITLE
Coq-programs

### ISSUE THREAD

**Issue by andreas-roehler** [williamdemeo/Coq#1]
Maybe rename repo to coq-programs?

**Comment by williamdemeo** [comment]
Maybe give a reason for opening this issue?  

Probably I will change the name of this repo, or simply delete it since I have another repo, also called Coq, that is more current.  

But I'm curious, why do you suggest this change?  Should there be only one repo in the world called Coq?  Perhaps you are right, but surely no one will mistake this repository for the official Coq repo.

Also, if you do a search for Coq on github, you will see that many repos are simply called Coq.  Is this a problem?

**Comment by andreas-roehler** [comment]
Am 26.07.2015 um 17:17 schrieb William DeMeo:
>
> Maybe give a reason for opening this issue?
>
> Probably I will change the name of this repo, or simply delete it 
> since I have another repo, also called Coq, that is more current.
>
> But I'm curious, why do you suggest this change? Should there be only 
> one repo in the world called Coq? Perhaps you are right, but surely no 
> one will mistake this repository for the official Coq repo.
>
> Also, if you do a search for Coq on github, you will see that many 
> repos are simply called Coq. Is this a problem?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/williamdemeo/Coq/issues/1#issuecomment-125006634>.
>

Not a problem in its the proper term, but not the best as it can be.

Why not give more info in order to speed up orientation?

Which relates to the other condidates mentioned also - just passed by yours.

If you think it isn't worth renaming, just close the issue, renamed my 
clone already...

Thanks providing the stuff.

**Comment by williamdemeo** [comment]
Okay, thanks for the feedback.  Glad you found the resources helpful.  You are right, the name could be better, and I will probably rename it.  (Of course, you are free to call your clone whatever you like. Or better yet, if you fork this repo, then you can suggest changes using pull requests.)

Also, this repo is not very well organized.  Honestly, I didn't expect others to make use of it.  I will probably combine this repo with [this other one](https://github.com/TypeFunc/Coq).  You might also find the latter one useful.
